parent(pam,bob).
parent(tom,bob).
parent(tom,liz).
parent(bob,ann).
parent(bob,pat).
parent(pat,jim).
female(pam).
female(liz).
female(ann).
female(pat).
male(tom).
male(jim).
male(bob).
father(X,bob):-parent(X,bob),male(X).
grandson(X,Y):-parent(Y,Z),parent(Z,X),male(X).
uncle(bill,sue):-parent(Z,sue),male(Z),brother(Z,bill),male(bill).
mother(marry,X):-parent(marry,X),female(marry).
brother(X,Y):-parent(Z,X),parent(Z,Y),male(X).
sister(X,Y):-parent(Z,X),parent(Z,Y),female(X).
grandfather(X,Y):-parent(X,Z),parent(Z,Y),male(X).
